import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import MainLayout from "@/components/layouts";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { LoadingProvider } from "@/components/providers/loading-provider";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <LoadingProvider>
            <MainLayout>
              {children}
            </MainLayout>
          </LoadingProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
